<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <noWarn>1591</noWarn>
    <IsPackable>True</IsPackable>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Project is not a test project -->
    <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.SubscriptionModule.Core\VirtoCommerce.SubscriptionModule.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    
    <PackageReference Include="VirtoCommerce.CustomerModule.Core" Version="3.1011.0" />
    <PackageReference Include="VirtoCommerce.NotificationsModule.Core" Version="3.1009.0" />
    <PackageReference Include="VirtoCommerce.Platform.Data" Version="3.1039.0" />
    <PackageReference Include="VirtoCommerce.Platform.Hangfire" Version="3.1039.0" />
    <PackageReference Include="VirtoCommerce.StoreModule.Core" Version="3.1005.0" />
  </ItemGroup>
</Project>